packages:
  - packages/*
  - internal/*

catalog:
  '@ctrl/tinycolor': ^3.6.1
  '@vue/shared': ^3.4.0
  '@vue/test-utils': ^2.4.0
  '@vueuse/core': ^10.9.0
  csstype: ^3.1.3
  lodash-unified: 1.0.3
  type-fest: ^4.0.0
  vue: ^3.4.0
